# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='user',
        ),
        migrations.RemoveField(
            model_name='join',
            name='wish',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='wisher',
        ),
        migrations.DeleteModel(
            name='Join',
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
