# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-21 16:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('wl_app', '0003_auto_20170729_1601'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wish',
            managers=[
                ('wishManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
