# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_app', '0004_auto_20171021_1613'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wish',
            managers=[
            ],
        ),
    ]
